// Mocks generated by Mockito 5.4.4 from annotations
// in dental_clinic/test/mocks/sqldb.mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dental_clinic/database/sqflite.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SqlDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqlDb extends _i1.Mock implements _i2.SqlDb {
  MockSqlDb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Database?> get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _i3.Future<_i4.Database?>.value(),
      ) as _i3.Future<_i4.Database?>);

  @override
  dynamic readData(String? sql) => super.noSuchMethod(Invocation.method(
        #readData,
        [sql],
      ));

  @override
  dynamic insertData(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      super.noSuchMethod(Invocation.method(
        #insertData,
        [
          sql,
          arguments,
        ],
      ));

  @override
  dynamic updateData(String? sql) => super.noSuchMethod(Invocation.method(
        #updateData,
        [sql],
      ));

  @override
  dynamic deleteData(String? sql) => super.noSuchMethod(Invocation.method(
        #deleteData,
        [sql],
      ));
}
